############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 5

[[main]]
parent = "About"
name = "Lecture Series"
url = "/lecture-series"

[[main]]
parent = "About"
name = "Contact"
url = "/contact"

[[main]]
name = "FAQs"
url = "/faqs"
weight = 3

[[main]]
  name = "Proceedings"
  url = "/proceedings"
  weight = 2

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

