############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 5

[[main]]
parent = "About"
name = "Lecture Series"
url = "/lecture-series"

[[main]]
parent = "About"
name = "Contact"
url = "/contact"

[[main]]
name = "FAQs"
url = "/faqs"
weight = 3

[[main]]
weight = 4
name = "Pages"

##[[main]]
##parent = "Pages"
##name = "Blog"
##url = "/blog"

[[main]]
  name = "Proceedings"
  url = "/proceedings"
  weight = 2



[[main]]
parent = "Pages"
name = "Authors"
url = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
url = "/categories"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
